# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://triangleidea.com
date_format: "ordinal"
title: ITriangle
subtitle: "To become a programmer just because I like it!"
description: "ITriangle的个人博客"
keywords: 
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: San Jiao
organization: CTGU, Inc.
organization_url: https://triangleidea.com
location: Shenzhen, China
email: jiaotriangle@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  # -
  #   href: /links/
  #   label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: ITriangle/itriangle.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: ITriangle
zhihu_username: ITriangle
# weibo_username: ITriangle
# douban_username: ITriangle
# facebook_username: ITriangle
twitter_username: ITriangle

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: ITriangle
disqus_username: disqus_JJbygqY8WO
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
# skill_software_keywords: [Java, C++, Python, Design Patterns]
# skill_mobile_app_keywords: [Android, Reverse Engineering]
# skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
